### ISSUE TITLE
aarch64-apple-darwin on github mac-os runner casing issues

### ISSUE THREAD

**Issue by C0D3-M4513R** [moonrepo/setup-rust#13]
[logs_macos_aarch64.txt](https://github.com/moonrepo/setup-rust/files/12707115/logs_macos_aarch64.txt) (for when logs get deleted)
from https://github.com/C0D3-M4513R/DexProtectOscRS/actions/runs/6285427718/job/17067798487?pr=3#logs

![image](https://github.com/moonrepo/setup-rust/assets/28912031/11cc6c98-2dc5-4900-8f0b-0b1c38d3706b)

**Comment by milesj** [comment]
@C0D3-M4513R 

Not sure what the fix is here? Looks like you're trying to install arm64 on an x64 machine. That won't work.
