### ISSUE TITLE
Add a flag to install rustup if it doesn't exist

### ISSUE THREAD

**Issue by prabirshrestha** [moonrepo/setup-rust#8]
README explicitly says it doesn't install rustup if it isn't found. I'm using [gitea with actions](https://blog.gitea.io/2022/12/feature-preview-gitea-actions/) and noticed that it didn't work due to missing rustup. Is it possible to have an explicit flag `install_rustup: true`?

**Comment by milesj** [comment]
@prabirshrestha The rustup-init script is very interactive, and I wasn't sure if bypassing all of it was the best approach.

**Comment by prabirshrestha** [comment]
Probably can pass `-y` flag to accept default.

```bash
curl -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
source ~/.cargo/env
```

**Comment by milesj** [comment]
Available in v1.
